spring.application.name=taskmanagement

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagement
spring.datasource.username=taskuser
spring.datasource.password=taskpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080
